dist: xenial

install:
  - |  # install hugo
    wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_extended_0.59.1_Linux-64bit.tar.gz &&\
    tar -zxf /tmp/hugo.tar.gz -C /tmp &&\
    mv /tmp/hugo .

  - |  # init submoudles
    git submodule init
    git submodule update --recursive --remote

script:
  - |  # build site
    HUGO_ENV=production ./hugo -v --minify -d dist

after_success:
  - |  # deploy gh-pages
    git clone "https://moreal:$GITHUB_TOKEN@github.com/moreal/blog.moreal.dev"
    pushd blog.moreal.dev
      git checkout gh-pages
      git rm -r .
      cp -r ../dist/* .
      cp -r ../CNAME .
      git add .
      git commit -m "Deploy blog.moreal.dev $TRAVIS_COMMIT" --allow-empty
      git push -f origin gh-pages
    popd

branches:
  only:
  - master
