baseURL = "https://moreal.github.io/blog"
languageCode = "en-us"
title = "Moreal"
theme = "m10c"

[[params.social]]
  name = "github"
  url = "https://github.com/moreal"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"